### PR TITLE
Allow passing of minimum connection timeout for connect/reconnect

### PR DESCRIPTION
**Pull request by Glockenbeat**
This should help to prevent issue #377 from happening and also makes the proposed workaround unnecessary by allowing the configuration of an optional minimumTimeout (default: 1000ms as before) when instantiating the SubscriptionClient.

Existing option timeout for the maximum timeout in the backoff was not renamed in order to stay backwards compatible.

### CODE REVIEW

**Comment by Glockenbeat** [comment]
CI is failing here but working perfectly fine locally when using the same configuration as Travis. Also test is failing in server code, changes were only done to client. Any ideas?

**Comment by SeanPercy** [comment]
@hwillson @trevorblades @NeoPhi sorry for bothering but since you guys are authorized to approve pull requests, it would be great if this one could be merged, in order to solve issue #377

**Comment by ToonvanStrijp** [comment]
@Glockenbeat can you resolve the merge conflicts?

@hwillson @trevorblades @NeoPhi  any update on this? :)

**Comment by jedwards1211** [comment]
@NeoPhi 
# it's been a year and a half, merge this yesterday

**Comment by laddi-netapp** [comment]
@Glockenbeat can you update the merge request to fix the conflicts, please?  This will solve a problem we are having with our production environment and we would prefer to use a released version of this component instead of having to make a local version...

**Comment by Glockenbeat** [comment]
PR is up to date now, however, it is open since more than 1.5 years and there has barely been any activity in this repo. Shame.
Also there are CI errors which are present in about every PR right now.

Guess this package is dead.

**Comment by jedwards1211** [comment]
@hwillson @NeoPhi @trevorblades

spamming you guys again

**Comment by trevorblades** [comment]
@jedwards1211 I don't have any useful insight or ownership over this package. My commits have been in the form of updating docs infrastructure. Sorry I can't be of more help here!

If you or somebody in this PR would be willing to take over maintaining this repo, that might be something that the OSS team at Apollo would be willing to talk about, but I don't want to speak for them.

**Comment by Glockenbeat** [comment]
Since I am actually not using this package anymore I'd like to skip.

**Comment by jedwards1211** [comment]
@trevorblades okay, do you know what channels I should contact folks through to volunteer for that?

**Comment by trevorblades** [comment]
@jedwards1211 please check out this thread for some discussion about the future of this repo: https://github.com/apollographql/subscriptions-transport-ws/issues/777

**Pull request closed without merging**
