### PR TITLE
Fix websocket reconnection

### PR DESCRIPTION
**Pull request by jpgarcia**
TODO:

- [x] Make sure all of the significant new logic is covered by tests
- [x] Rebase your changes on master so that they can be merged easily
- [x] Make sure all tests and linter rules pass
- [x] Update CHANGELOG.md with your change

### CODE REVIEW

**Comment by mxstbr** [comment]
Going to test this in our app and see if this resolves things!

**Comment by rimiti** [comment]
+1

**Comment by jpgarcia** [comment]
Sorry guys, Unfortunately I'm very busy right now and I have no time to spend on creating new tests. 

I've just applied the fix suggested by @pandemosth (https://github.com/apollographql/subscriptions-transport-ws/issues/295#issuecomment-339323133) and make sure that all tests passed.

BTW I've applied the patch in my project and it's working like a charm!

**Comment by damour** [comment]
Add test in https://github.com/apollographql/subscriptions-transport-ws/pull/439

**Comment by NeoPhi** [comment]
Closed via: https://github.com/apollographql/subscriptions-transport-ws/pull/439

**Pull request closed without merging**
