### PR TITLE
fix: do not send GQL_STOP after GQL_COMPLETED is received

### LINKED ISSUE #711: GQL_STOP sent after "complete" from server
It looks like a `GQL_STOP` message is being sent from the client, _after_ receiving a completion message back from the server, resulting in the server then returning an error since the subscription is no longer active.

Screenshot 2019-12-06 at 16 08 36

My expectation would be that if the server has initiated a `complete` message, the client should silently unsubscribe.

FWIW, I'm using [gqlgen](https://gqlgen.com/) in Go for the server.

### PR DESCRIPTION
**Pull request by onhate**
fix #711

### CODE REVIEW

**Comment by onhate** [comment]
@abernix WDYT?

**Comment by onhate** [comment]
@trevorblades let me know your thoughts.

**Comment by onhate** [comment]
@hwillson @stubailo could you shed a light on here? who is the responsible for this repository?

**Comment by onhate** [comment]
I have publish a parallel version while that, if anyone want to get access to this fix/improvement feel free to use it

https://www.npmjs.com/package/@texelz/subscriptions-transport-ws/v/0.9.1-6.no-gql-stop

**Comment by fredli74** [comment]
This change causes server memory leaks. #805

I personally do not think it's a bad client fix, but the server does not handle it correctly.

**Pull request merged**
