### PR TITLE
Set this.client to null before calling client.close()

### PR DESCRIPTION
**Pull request by ibash**
client.close can sometimes lead to a synchronous call to close. This
leads to the error:
[TypeError: Cannot set property 'onopen' of null]

This change sets client to null before calling onClose, so that the
second synchronous call does not try to cleanup the client.

TODO:

- [x] Make sure all of the significant new logic is covered by tests
- [x] Rebase your changes on master so that they can be merged easily
- [x] Make sure all tests and linter rules pass
- [x] Update CHANGELOG.md with your change

### CODE REVIEW

**Comment by alexandre-kairn** [comment]
Should fix #808

**Comment by BenSwennen** [comment]
Any updates on this?

**Review by ml242 — APPROVED** [review]

**Comment by tyagow** [comment]
@ibash sorry to bother you, any estimation on fixing this conflict? I am more than happy to help just not sure how...
Facing this issue right now and I don't want to patch the package...

**Comment by ibash** [comment]
@tyagow Unfortunately there's nothing I can do, it's up to the apollo team to merge it and it seems like they've abandoned this package :(

Your best bet is patching the package, happy to help you set that up if need be. But in general:
1. Follow setup instructions [here](https://github.com/ds300/patch-package#set-up)
2. Edit `node_modules/subscriptions-transport-ws/dist/client.js` with [these changes](https://github.com/apollographql/subscriptions-transport-ws/issues/808#issuecomment-767479927)
3. Run `npx patch-package subscriptions-transport-ws`

**Comment by ibash** [comment]
@glasser any chance this can be merged?

**Comment by tyagow** [comment]
> @tyagow Unfortunately there's nothing I can do, it's up to the apollo team to merge it and it seems like they've abandoned this package :(
> 
> Your best bet is patching the package, happy to help you set that up if need be. But in general:
> 
> 1. Follow setup instructions [here](https://github.com/ds300/patch-package#set-up)
> 2. Edit `node_modules/subscriptions-transport-ws/dist/client.js` with [these changes](https://github.com/apollographql/subscriptions-transport-ws/issues/808#issuecomment-767479927)
> 3. Run `npx patch-package subscriptions-transport-ws`

Thanks for the instructions, I am using this approach.

**Comment by ml242** [comment]
This package is used by Apollo Client which makes the errors extra irritating as I would have to fork and pin both packages.

**Pull request closed without merging**
