### PR TITLE
chore(lodash): require specific lodash/assign module

### PR DESCRIPTION
**Pull request by WesleydeSouza**
Importing from `lodash` loads the entire lib into memory unnecessarily.

### CODE REVIEW

**Comment by WesleydeSouza** [comment]
It seems the build fail is not related to this PR changes.

**Comment by mistic** [comment]
@WesleydeSouza I think my pr should fix this build fail on your pr :)

**Comment by WesleydeSouza** [comment]
@mistic yeah, for sure the browser build is now massively smaller (~83 kB). 

And it seems the intended package was in fact `lodash.assign`, the previous require will fail if no library depends on `lodash` (which is fine for people that use `webpack` since `async` depends on `lodash` 😛 )

I've switched to that, but it seems I've done something wrong with the type declarations and test is failing again, I'm not very familiar with TypeScript.

**Comment by dotansimha** [comment]
@WesleydeSouza why changing `import` to `require` ? Your typings looks fine and I think you can use `import` here.

**Comment by dotansimha** [comment]
@WesleydeSouza never mind, got it :) 

Thanks @WesleydeSouza !

**Pull request merged**
