### PR TITLE
Add src files for source-maps

### PR DESCRIPTION
**Pull request by DanielMSchmidt**
An alternative to this would be #513. Both fix the problem of source maps pointing into the void

This lets the current source maps point to a valid file instead of the void

TODO:

- [X] Make sure all of the significant new logic is covered by tests
- [X] Rebase your changes on master so that they can be merged easily
- [X] Make sure all tests and linter rules pass
- [ ] Update CHANGELOG.md with your change

### CODE REVIEW

**Comment by niekert** [comment]
Would be really nice if this could get merged or some alternative strategies are provided 🙏

**Comment by meuter** [comment]
Any idea when this will be merged? 😅 🙏 (tx!)

**Comment by MrTibbles** [comment]
+1 to this getting merged.

**Comment by hwillson** [comment]
Thanks for this @DanielMSchmidt - we're going to go with https://github.com/apollographql/subscriptions-transport-ws/pull/513 for now.

**Pull request closed without merging**
