### PR TITLE
Use print from graphql directly instead of from graphql-tag

### PR DESCRIPTION
**Pull request by xavcz**
TODO:
---
- [x] Make sure all of the significant new logic is covered by tests
- [x] Rebase your changes on master so that they can be merged easily
- [x] Make sure all tests and linter rules pass
- [x] Update CHANGELOG.md with your change

What's up?
---
Hey! While updating `meteor/apollo` to use this package (yay! :rocket:), we encountered the warning about deprecation of `print` from `graphql-tag` (https://github.com/apollographql/meteor-integration/issues/87).

Following discussions from https://github.com/apollographql/graphql-tag/issues/54 & others PRs/issues related, I've made the change & I've tried it locally: tests pass and it works.

I assumed that `graphql` should be then in `dependencies` more than `devDependencies`, right?

### CODE REVIEW

**Comment by Urigo** [comment]
Cool, thanks @xavcz

**Comment by kachkaev** [comment]
Would it be possible to release a new version of `subscriptions-transport-ws` guys? Both `0.5.4`  and `0.5.5-alpha.0` seem to be causing the warning in the console:

```
Warning - the `printer` exports from `graphql-tag` will be removed in the next major version.
See https://github.com/apollographql/graphql-tag/issues/54 for more information.
```

**Comment by Anthonyzou** [comment]
Yeah if you can release a new version that would be great.

**Comment by Urigo** [comment]
@Anthonyzou just released `0.5.5`.   sorry for the delay

**Pull request merged**
