### PR TITLE
feat(NA): add new connection events.

### PR DESCRIPTION
**Pull request by mistic**
Guys ( @Urigo @DxCx @helfer @dotansimha @NeoPhi ) this PR enables the new connection events discussed in #136. 

No breaking change was introduced, however I coded some deprecation warnings.

### CODE REVIEW

**Comment by dotansimha** [comment]
@mistic please also update the CHANGELOG :)

**Comment by mistic** [comment]
@dotansimha done 😄

**Comment by Urigo** [comment]
@mistic looks great!  could you just resolve the conflicts?

**Comment by mistic** [comment]
@Urigo done :)

**Comment by Urigo** [comment]
thank you again @mistic !

**Pull request merged**
